(() => {
  const RPCS=['https://ethereum-rpc.publicnode.com','https://1rpc.io/eth'];
  const $=id=>document.getElementById(id); const form=$('scanForm'), source=$('source'), destination=$('destination');
  const errorBox=$('errorBox'), empty=$('reportEmpty'), live=$('reportLive'), statusLarge=$('statusLarge'), progress=$('progress'), scanButton=$('scanButton');
  const isAddress=v=>/^0x[0-9a-fA-F]{40}$/.test(v.trim());
  const quantity=v=>BigInt(v); const fmtEth=v=>{const n=quantity(v),whole=n/10n**18n,dec=(n%10n**18n).toString().padStart(18,'0').slice(0,6).replace(/0+$/,'');return `${whole}${dec?'.'+dec:''}`};
  async function rpcBatch(calls){let last;for(const url of RPCS){try{const body=calls.map((c,i)=>({jsonrpc:'2.0',id:i+1,...c}));const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`RPC ${r.status}`);const data=await r.json();const ordered=body.map(b=>{const x=data.find(v=>v.id===b.id);if(!x||x.error)throw new Error(x?.error?.message||'Incomplete RPC response');return x.result});return ordered}catch(e){last=e}}throw last||new Error('Ethereum RPC unavailable')}
  function classify(code,nonce){if(/^0xef0100[0-9a-f]{40}$/i.test(code))return['Delegated wallet','contract'];if(code!=='0x')return['Contract account','contract'];if(quantity(nonce)>0n)return['Signing exposure indicated','exposed'];return['No signing indicator','safe']}
  async function inspectPair(a,b){const [chain,block]=await rpcBatch([{method:'eth_chainId',params:[]},{method:'eth_getBlockByNumber',params:['latest',false]}]);if(chain!=='0x1')throw new Error('Provider did not return Ethereum mainnet');const tag=block.number;const [ac,an,ab,bc,bn]=await rpcBatch([{method:'eth_getCode',params:[a,tag]},{method:'eth_getTransactionCount',params:[a,tag]},{method:'eth_getBalance',params:[a,tag]},{method:'eth_getCode',params:[b,tag]},{method:'eth_getTransactionCount',params:[b,tag]}]);const [block2]=await rpcBatch([{method:'eth_getBlockByNumber',params:[tag,false]}]);if(block.hash!==block2.hash)throw new Error('Block evidence changed during inspection');return {block,source:{code:ac,nonce:an,balance:ab},destination:{code:bc,nonce:bn}}}
  function setBusy(v){scanButton.disabled=v;scanButton.textContent=v?'Reading Ethereum…':'Run live preflight';progress.style.display=v?'block':'none'}
  form.addEventListener('submit',async e=>{e.preventDefault();errorBox.classList.remove('show');const a=source.value.trim(),b=destination.value.trim();if(!isAddress(a)||!isAddress(b)){errorBox.textContent='Enter two valid 42-character Ethereum addresses.';errorBox.classList.add('show');return}if(a.toLowerCase()===b.toLowerCase()){errorBox.textContent='Source and destination must be different.';errorBox.classList.add('show');return}empty.classList.add('hide');live.classList.add('show');statusLarge.className='status-large';statusLarge.textContent='Reading network…';setBusy(true);try{const r=await inspectPair(a,b),[label,tone]=classify(r.destination.code,r.destination.nonce);statusLarge.textContent=label;statusLarge.className=`status-large ${tone}`;$('sourceNonce').textContent=quantity(r.source.nonce).toString();$('sourceBalance').textContent=`${fmtEth(r.source.balance)} ETH`;$('destNonce').textContent=quantity(r.destination.nonce).toString();$('destCode').textContent=r.destination.code==='0x'?'EMPTY':/^0xef0100/i.test(r.destination.code)?'EIP-7702':'PRESENT';$('blockEvidence').textContent=`${quantity(r.block.number)} / ${r.block.hash}`;showToast(tone==='safe'?'Destination has no onchain signing indicator. Ownership is still not proven.':'Destination requires manual review before any transfer.')}catch(err){statusLarge.textContent='Inspection unavailable';statusLarge.className='status-large contract';errorBox.textContent=`Live read failed: ${err.message}. No wallet request was made.`;errorBox.classList.add('show')}finally{setBusy(false)}});
  $('demoButton').addEventListener('click',()=>{source.value='0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045';destination.value='0x1234567890123456789012345678901234567890';showToast('Public example loaded. Results come from live Ethereum state.')});
  document.querySelectorAll('[data-paste]').forEach(btn=>btn.addEventListener('click',async()=>{try{const t=await navigator.clipboard.readText();const field=$(btn.dataset.paste);field.value=t.trim();field.dispatchEvent(new Event('input',{bubbles:true}))}catch{showToast('Clipboard access was unavailable. Paste the address manually.')}}));
  document.querySelectorAll('.mode-action').forEach(btn=>btn.addEventListener('click',()=>{showToast(btn.dataset.mode==='direct'?'Direct Route selected: no custom approvals or custody.':'Bounded Migrator is a future audited module; execution remains disabled.')}));
  let toastTimer;function showToast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),4200)}
})();
